const fs=require('fs');const path=require('path');const {execSync}=require('child_process');const {google}=require('googleapis');const puppeteer=require('puppeteer-core');
const GROQ_API_KEY=process.env.GROQ_API_KEY,YT_CLIENT_ID=process.env.YT_CLIENT_ID,YT_CLIENT_SECRET=process.env.YT_CLIENT_SECRET,YT_REFRESH_TOKEN=process.env.YT_REFRESH_TOKEN;const WORK_DIR=path.join(__dirname,'work'),FRAMES_DIR=path.join(WORK_DIR,'frames'),STATE_FILE=path.join(__dirname,'last-article.json'),REVIEW_FILE=path.join(WORK_DIR,'review.txt'),BGM_FILE=path.join(__dirname,'assets','bgm.mp3'),TELUGU_FONT='/usr/share/fonts/truetype/noto/NotoSansTelugu-SemiBold.ttf',CHROME_PATH=process.env.CHROME_PATH||['/usr/bin/google-chrome-stable','/usr/bin/google-chrome','/usr/bin/chromium-browser'].find(p=>fs.existsSync(p));
const PRIMARY_MODEL='openai/gpt-oss-120b',FALLBACK_MODEL='openai/gpt-oss-20b',MIN_WORDS=16,MAX_WORDS=36,CHUNK_WORDS=3,CHUNK_HOLD_SECONDS=1.85,TYPE_STEP_SECONDS=.055,TYPE_BUDGET_SECONDS=1.25,TAIL_PAD_SECONDS=1.2,HOOK_HOLD_SECONDS=1.7,CTA_LINE_HOLD_SECONDS=1.2,CTA_FINAL_HOLD_SECONDS=1.8,TELUGU_RANGE=/[ఀ-౿]/;
const TOP_LABELS=['MINDSET 🧠','LIFE LESSON 💡','TRUE WORDS ⏳','SILENT POWER 🤫','REALITY OF LIFE 💯','INNER POWER 🔥','NEW BEGINNING 🌅','STAY CALM 🍃','KEEP GROWING 🌱','BE BRAVE 🦁'];
const MOOD_TOP_LABEL=[[/trust|betray/i,'MINDSET 🧠'],[/success|hard.?work|effort/i,'LIFE LESSON 💡'],[/time|patience/i,'TRUE WORDS ⏳'],[/silen|matur/i,'SILENT POWER 🤫'],[/money|wealth|relation/i,'REALITY OF LIFE 💯'],[/determin|focus/i,'MINDSET 🧠'],[/resilien|strength/i,'INNER POWER 🔥'],[/hope|new.?begin|change/i,'NEW BEGINNING 🌅'],[/calm|peace/i,'STAY CALM 🍃'],[/growth|grow/i,'KEEP GROWING 🌱'],[/courage|brave|opportunit/i,'BE BRAVE 🦁']];
const MOOD_EMOJI=[[/determin/i,'💪'],[/resilien|strength/i,'🔥'],[/hope/i,'🌅'],[/focus/i,'🎯'],[/calm/i,'🍃'],[/growth/i,'🌱'],[/courage|brave/i,'🦁'],[/trust|relation/i,'❤️'],[/time|patience/i,'⏳']];
function pickEmoji(mood){const hit=MOOD_EMOJI.find(([re])=>re.test(mood||''));return hit?hit[1]:'✨'}
const CTA_PRIMARY=[`ఈ మాట నచ్చితే <span class="accent">❤️ Like</span> చేయండి`,`మీ అభిప్రాయం <span class="accent">💬 కామెంట్</span>లో చెప్పండి`,`మీ వాళ్లకి కూడా <span class="accent">🔗 Share</span> చేయండి`];
const CTA_SUBSCRIBE=`ఇలాంటి నిజమైన మాటల కోసం <span class="accent">Subscribe 🔔</span> అవ్వండి`;
function log(x){console.log(`[${new Date().toISOString()}] ${x}`)};async function get(url,options={},timeout=30000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{return await fetch(url,{...options,signal:c.signal})}finally{clearTimeout(t)}};async function sleep(ms){return new Promise(r=>setTimeout(r,ms))};function countWords(s){return String(s||'').trim().split(/\s+/).filter(Boolean).length};function normalize(s){return String(s||'').replace(/[“”"']/g,'').replace(/\s+/g,' ').trim()};function latin(s){return String(s||'').match(/[A-Za-z]{2,}/g)||[]};function state(){try{return JSON.parse(fs.readFileSync(STATE_FILE,'utf8'))}catch{return {runCount:0,used:[]}}};function saveState(t,s,i){const st=state();fs.writeFileSync(STATE_FILE,JSON.stringify({runCount:(st.runCount||0)+1,lastTitle:t,lastDate:new Date().toISOString(),used:[...(st.used||[]),{title:t,screen:s,image:i}]},null,2))};function dup(t,s,i){return (state().used||[]).some(x=>x.title===t||x.screen===s||(i&&x.image===i))};function validTelugu(s,min,max){const c=normalize(s);return countWords(c)>=min&&countWords(c)<=max&&latin(c).length===0&&TELUGU_RANGE.test(c)&&/[.!?…]$/.test(c)};
function pickTopLabel(m){const hit=MOOD_TOP_LABEL.find(([re])=>re.test(m||''));return hit?hit[1]:'LIFE LESSON 💡'}
const FALLBACKS=[
  {title:'మొదటి అడుగు',screen:'కష్టపడిన ప్రతి క్షణం వృథా కాదు, ఆ కష్టం వెనుక దాగి ఉన్న అనుభవం మనకి కొత్త బలాన్ని ఇస్తుంది, అదే బలం మనల్ని ముందుకు నడిపిస్తుంది.',highlightWords:['బలాన్ని'],hook:'ప్రతి కష్టం మనలో ఏమి పెంచుతుందో ఎప్పుడైనా గమనించారా?',mood:'quiet determination',topLabel:'MINDSET 🧠',image:'lone figure taking the first step onto a misty mountain trail at sunrise, cinematic vertical photography'},
  {title:'కొత్త పాఠం',screen:'ప్రతి వైఫల్యం వెనుక ఒక కొత్త పాఠం దాగి ఉంటుంది, దాన్ని అర్థం చేసుకున్నప్పుడు మనలోని బలం మరింత పెరుగుతుంది, అదే బలం కొత్త దారిని చూపిస్తుంది.',highlightWords:['పాఠం'],hook:'వైఫల్యం మనకు నిజంగా ఏం నేర్పుతుందో తెలుసా?',mood:'calm resilience',topLabel:'LIFE LESSON 💡',image:'person standing before a cracked open door with warm light spilling through, cinematic vertical photography'},
  {title:'లోపల బలం',screen:'మనలోని ఆత్మవిశ్వాసం ప్రతి కష్టమైన రోజును దాటించే అసలైన బలం, అది నిశ్శబ్దంగా మనతో నడుస్తుంది, అవసరమైనప్పుడు ధైర్యంగా ముందుకు తీసుకెళ్తుంది.',highlightWords:['బలం'],hook:'నిజమైన బలం మనలోనే ఉందని ఎప్పుడైనా అనిపించిందా?',mood:'hopeful strength',topLabel:'INNER POWER 🔥',image:'silhouette of a person standing tall against a stormy sky that is clearing to sunlight, cinematic vertical photography'},
  {title:'సహనం ఫలం',screen:'సహనంతో ఎదురుచూసిన ప్రతి క్షణం వృథా కాదు, కాలం గడిచేకొద్దీ మన ప్రయత్నం బలపడుతుంది, సరైన సమయంలో దానికి తగిన ఫలితం కనిపిస్తుంది.',highlightWords:['ఫలితం'],hook:'సహనం ఎప్పుడూ ఎందుకు విలువైనదో తెలుసా?',mood:'warm encouragement',topLabel:'TRUE WORDS ⏳',image:'a single sapling growing through cracked rock in warm afternoon light, cinematic vertical photography'},
  {title:'గమ్యం వైపు',screen:'లక్ష్యం వైపు వేసే ప్రతి చిన్న అడుగు కూడా విలువైనదే, ఆ అడుగులు కలిసినప్పుడు దూరమైన గమ్యం దగ్గరవుతుంది, నమ్మకంతో ముందుకు సాగాలి.',highlightWords:['గమ్యం'],hook:'చిన్న అడుగులు ఎంత దూరం తీసుకెళ్తాయో ఎప్పుడైనా ఆలోచించారా?',mood:'steady focus',topLabel:'KEEP GROWING 🌱',image:'person walking a long winding path toward a distant sunrise on the horizon, cinematic vertical photography'},
  {title:'నిశ్శబ్ద శ్రమ',screen:'నిశ్శబ్దంగా చేసే శ్రమకు వెంటనే గుర్తింపు రావకపోవచ్చు, కానీ ప్రతి రోజు చేసిన ప్రయత్నం లోపల బలాన్ని పెంచుతుంది, ఒక రోజు ఫలితం తానే మాట్లాడుతుంది.',highlightWords:['శ్రమకు'],hook:'ఎవరూ చూడని శ్రమకు నిజమైన విలువ ఉంటుందా?',mood:'quiet determination',topLabel:'SILENT POWER 🤫',image:'solitary person working alone before dawn in a simple workshop, soft window light, cinematic vertical photography'},
  {title:'మార్పు బలం',screen:'మార్పు మొదట భయంగా అనిపించవచ్చు, కానీ దాన్ని స్వీకరించినప్పుడు మనలో కొత్త బలం మేల్కొంటుంది, అదే బలం ముందున్న దారిని సులభం చేస్తుంది.',highlightWords:['బలం'],hook:'మార్పు మనలో దాచిన ఏ బలాన్ని బయటకు తెస్తుందో తెలుసా?',mood:'new beginning',topLabel:'NEW BEGINNING 🌅',image:'person stepping from a shadowed doorway into warm morning light, cinematic vertical photography'},
  {title:'నమ్మకం విలువ',screen:'నిన్ను నువ్వు నమ్మడం అంటే ప్రతి సమస్య సులభమవుతుందని కాదు, కానీ ప్రతి సమస్యను ఎదుర్కొనే ధైర్యం నీలో పెరుగుతుందని అర్థం.',highlightWords:['నమ్మడం'],hook:'మనల్ని మనం నమ్మడం ఎందుకు అంత ముఖ్యమో తెలుసా?',mood:'inner strength',topLabel:'MINDSET 🧠',image:'confident solitary figure overlooking a vast valley at sunrise, cinematic vertical photography'},
  {title:'కాలం పాఠం',screen:'కాలం మనకు కొన్ని సమాధానాలు మాటలతో ఇవ్వదు, అనుభవాల ద్వారా చూపిస్తుంది, అర్థం చేసుకున్న కొద్దీ జీవితం మీద మన దృష్టి మరింత స్పష్టమవుతుంది.',highlightWords:['అనుభవాల'],hook:'కాలం మాటలు లేకుండా నేర్పే పాఠాలు ఏమిటో గమనించారా?',mood:'quiet wisdom',topLabel:'TRUE WORDS ⏳',image:'old path through trees with morning mist and soft sunlight, cinematic vertical photography'},
  {title:'కష్టంలో అవకాశం',screen:'కష్టం వచ్చినప్పుడు దారి మూసుకుపోయిందని అనిపించవచ్చు, కానీ అదే పరిస్థితి మనలో దాగి ఉన్న సామర్థ్యాన్ని బయటకు తెచ్చే అవకాశంగా మారుతుంది.',highlightWords:['సామర్థ్యాన్ని'],hook:'కష్టమే మనలో దాగిన ఏ శక్తిని బయటకు తెస్తుందో తెలుసా?',mood:'resilient strength',topLabel:'BE BRAVE 🦁',image:'person standing before a steep mountain trail after rain, sunlight breaking through clouds, cinematic vertical photography'}
];
function parse(raw){const title=raw.match(/TITLE:\s*(.+)/i)?.[1]?.trim()||'తెలుగు జీవిత సత్యం';const sr=(raw.match(/SCREEN:\s*([\s\S]*?)(?=\nHOOK:|\nMOOD:|\nTOP_LABEL:|\nIMAGE_PROMPT:|$)/i)?.[1]||'').replace(/["“”]/g,'').replace(/\s+/g,' ').trim();const highlightWords=[...sr.matchAll(/\*([^\s*]+)\*/g)].map(m=>m[1]);const screen=sr.replace(/\*/g,'');const hook=normalize(raw.match(/HOOK:\s*([\s\S]*?)(?=\nMOOD:|\nTOP_LABEL:|\nIMAGE_PROMPT:|$)/i)?.[1]||'');const mood=raw.match(/MOOD:\s*(.+)/i)?.[1]?.trim()||'quiet determination';const cleanLabel=s=>String(s||'').replace(/["'“”]/g,'').replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}️]/gu,'').replace(/\s+/g,' ').trim().toLowerCase();const topLabelRaw=raw.match(/TOP_LABEL:\s*(.+)/i)?.[1]?.trim()||'';const topLabel=TOP_LABELS.find(l=>cleanLabel(l)===cleanLabel(topLabelRaw))||'';const image=raw.match(/IMAGE_PROMPT:\s*([\s\S]*?)(?=\n$|$)/i)?.[1]?.trim()||'';return{title,screen,hook,mood,topLabel,image,highlightWords}}
async function groq(prompt,model=PRIMARY_MODEL,attempt=1){const r=await get('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${GROQ_API_KEY}`},body:JSON.stringify({model,temperature:.72,max_tokens:model===FALLBACK_MODEL?6000:1536,messages:[{role:'user',content:prompt}]})});const d=await r.json();if(r.status===429&&attempt<=3){await sleep(15000);return groq(prompt,model,attempt+1)}if(!d.choices?.[0]?.message?.content)throw new Error(`Groq HTTP ${r.status}`);return d.choices[0].message.content.replace(/<think>[\s\S]*?<\/think>/gi,'').trim()}
async function makeQuote(){const prompt=`Create ONE completely original motivational life-wisdom quote for a Telugu YouTube Short. Use natural contemporary Telugu, not translation. Do not quote or reference any real person, book, movie, song, scripture, or existing proverb — the thought must be entirely original. Do not make factual claims, statistics, or promises about health, money, or results.\nTITLE: 2-4 Telugu words.\nSCREEN: exactly 16-36 Telugu words, one coherent thought. Mark EXACTLY ONE emotionally important word by surrounding it with asterisks, e.g. *బలం*. Do not use asterisks anywhere else.\nHOOK: 4-20 natural Telugu words.\nMOOD: 2-4 English mood words only.\nTOP_LABEL: pick the single best-fitting option from this exact list (copy it exactly, including the emoji): ${TOP_LABELS.join(' | ')}\nIMAGE_PROMPT: detailed English cinematic 9:16 image prompt, no text/watermark/collage.\nReturn exactly six lines: TITLE, SCREEN, HOOK, MOOD, TOP_LABEL, IMAGE_PROMPT.`;for(let i=0;i<6;i++){try{const q=parse(await groq(prompt,i<3?PRIMARY_MODEL:FALLBACK_MODEL));if(validTelugu(q.screen,MIN_WORDS,MAX_WORDS)&&validTelugu(q.hook,4,20)&&q.image&&!dup(q.title,q.screen,q.image)&&q.highlightWords.length===1)return q}catch(e){log(`quote ${i+1} failed: ${e.message}`)}}const pool=FALLBACKS.filter(f=>!dup(f.title,f.screen,f.image));log(`Groq did not pass validation; using curated original fallback (${pool.length}/${FALLBACKS.length} unused)`);return (pool.length?pool:FALLBACKS)[state().runCount%(pool.length||FALLBACKS.length)]}
async function makeImage(prompt){const enhanced=`${prompt}, vertical 9:16, cinematic still photograph, realistic natural human emotion, beautiful composition, soft depth of field, subtle film grain, no words, no letters, no logo, no watermark, no collage`;let last='unknown';for(let a=1;a<=3;a++){const url=`https://image.pollinations.ai/prompt/${encodeURIComponent(enhanced)}?width=1080&height=1920&nologo=true&seed=${Math.floor(Math.random()*1e9)}`;try{const r=await get(url,{},90000),b=Buffer.from(await r.arrayBuffer()),ct=String(r.headers.get('content-type')||'').toLowerCase();if(r.ok&&(ct.startsWith('image/')||b.length>=10000)){const p=path.join(WORK_DIR,'background.jpg');fs.writeFileSync(p,b);return p}last=`HTTP ${r.status}`}catch(e){last=e.message}if(a<3)await sleep(2500*a)}throw new Error(`AI image failed after 3 attempts: ${last}`)}
function escapeHtml(s){return String(s||'').replace(/</g,'&lt;').replace(/>/g,'&gt;')};function splitChunks(words){const c=[];for(let i=0;i<words.length;i+=CHUNK_WORDS)c.push(words.slice(i,i+CHUNK_WORDS));if(c.length>1&&c.at(-1).length===1)c[c.length-2].push(...c.pop());return c};function normalizeWord(w){return String(w||'').replace(/^[,.;:!?"'…]+|[,.;:!?"'…]+$/g,'')};function pickHighlightIndex(words,marks=[]){const m=marks.map(normalizeWord).filter(Boolean);return words.findIndex(w=>m.some(x=>normalizeWord(w)===x||normalizeWord(w).includes(x)||x.includes(normalizeWord(w))))};const SEG=new Intl.Segmenter('te',{granularity:'grapheme'});function graphemes(s){return Array.from(SEG.segment(s),x=>x.segment)};function inner(gs,hi,revealed){let rem=revealed,out=[];for(let i=0;i<gs.length&&rem>0;i++){const take=Math.min(rem,gs[i].length);if(take<=0)continue;out.push(`<span class="${i===hi?'hi':'w'}">${escapeHtml(gs[i].slice(0,take).join(''))}</span>`);rem-=take}return out.join(' ')};
function pageHtml(body,top,cta=''){const topHtml=top?`<div class="top"><span class="topPill">${escapeHtml(top)}</span></div>`:'';return `<!doctype html><html><head><meta charset="utf-8"><style>@font-face{font-family:t;src:url('file://${TELUGU_FONT}')}html,body{margin:0;width:1080px;height:1920px;background:transparent}.box{position:absolute;left:40px;top:565px;width:1000px;height:770px;display:flex;align-items:center;justify-content:center;padding:0 34px;box-sizing:border-box}.txt{font-family:t,sans-serif;font-size:66px;font-weight:700;line-height:1.45;color:#fff;text-align:center;text-shadow:0 2px 3px rgba(0,0,0,.85)}.hi{color:#ffd21f;text-shadow:0 2px 3px rgba(0,0,0,.85)}.top{position:absolute;top:190px;left:70px;width:940px;text-align:center;font:700 34px Arial,sans-serif;letter-spacing:1.2px;color:#fff;text-shadow:0 2px 4px rgba(0,0,0,.8)}.topPill{display:inline-block;padding:12px 28px;border-radius:26px;background:rgba(0,0,0,.38)}.cta{position:absolute;left:70px;right:70px;bottom:480px;text-align:center;font:700 34px/1.4 Arial,sans-serif;color:#fff;text-shadow:0 2px 4px rgba(0,0,0,.85)}.ctaBox{display:inline-block;padding:14px 28px;border-radius:28px;background:rgba(0,0,0,.42)}.accent{color:#ffd21f}.hookPill{display:inline-block;padding:26px 44px;border-radius:36px;background:rgba(0,0,0,.4);border:2px solid rgba(255,210,31,.55)}.hookTxt{font-family:t,sans-serif;font-size:56px;font-weight:800;font-style:italic;line-height:1.5;color:#ffd21f;text-shadow:0 2px 4px rgba(0,0,0,.9)}</style></head><body>${topHtml}<div class="box"><div class="txt">${body}</div></div>${cta}</body></html>`}
async function renderSequence(q,top){fs.mkdirSync(FRAMES_DIR,{recursive:true});const words=q.screen.trim().split(/\s+/),chunks=splitChunks(words),timeline=[],browser=await puppeteer.launch({headless:'new',executablePath:CHROME_PATH,args:['--no-sandbox','--disable-setuid-sandbox']}),page=await browser.newPage();await page.setViewport({width:1080,height:1920,deviceScaleFactor:1});try{
  // Opening hook frame: a scroll-stopping pattern-interrupt line held briefly before the quote
  // starts typing, since Shorts retention in the first ~2s weighs heavily on how far it's pushed.
  if(q.hook){await page.setContent(pageHtml(`<div class="hookPill"><span class="hookTxt">${escapeHtml(q.hook)}</span></div>`,top),{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);const hp=path.join(FRAMES_DIR,'hook.png');await page.screenshot({path:hp,omitBackground:true});timeline.push({path:hp,duration:HOOK_HOLD_SECONDS})}
  let prior='';for(let ci=0;ci<chunks.length;ci++){const cw=chunks[ci],hi=pickHighlightIndex(cw,q.highlightWords),gs=cw.map(graphemes),total=gs.reduce((n,g)=>n+g.length,0),steps=Math.min(Math.ceil(TYPE_BUDGET_SECONDS/TYPE_STEP_SECONDS),total),counts=[];for(let s=1;s<=steps;s++)counts.push(Math.min(total,Math.ceil(total*s/steps)));counts.push(total);let final='';for(let si=0;si<counts.length;si++){const cur=inner(gs,hi,counts[si]);final=cur;await page.setContent(pageHtml(prior?`${prior} ${cur}`:cur,top),{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);const p=path.join(FRAMES_DIR,`c${String(ci).padStart(3,'0')}_${si}.png`);await page.screenshot({path:p,omitBackground:true});timeline.push({path:p,duration:si===counts.length-1?Math.max(CHUNK_HOLD_SECONDS-(counts.length-1)*TYPE_STEP_SECONDS,TYPE_STEP_SECONDS)+(ci===chunks.length-1?TAIL_PAD_SECONDS:0):TYPE_STEP_SECONDS})}prior=prior?`${prior} ${final}`:final};
  // Rotate the first CTA slot (Like/Comment/Share) across runs instead of showing the identical
  // pair on every single video; Subscribe stays fixed as the final, strongest ask.
  const ctas=[`<div class="cta"><div class="ctaBox">${CTA_PRIMARY[state().runCount%CTA_PRIMARY.length]}</div></div>`,`<div class="cta"><div class="ctaBox">${CTA_SUBSCRIBE}</div></div>`];
  for(let i=0;i<ctas.length;i++){await page.setContent(pageHtml(prior,top,ctas[i]),{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);const p=path.join(FRAMES_DIR,`cta_${i}.png`);await page.screenshot({path:p,omitBackground:true});timeline.push({path:p,duration:CTA_LINE_HOLD_SECONDS+(i===ctas.length-1?CTA_FINAL_HOLD_SECONDS:0)})}}finally{await browser.close()}const lines=[];for(const f of timeline){lines.push(`file '${f.path}'`);lines.push(`duration ${f.duration.toFixed(3)}`)}lines.push(`file '${timeline.at(-1).path}'`);const listFile=path.join(FRAMES_DIR,'list.txt');fs.writeFileSync(listFile,lines.join('\n'));return{listFile,totalSeconds:timeline.reduce((s,f)=>s+f.duration,0)}}
async function render(image,q,top){const out=path.join(WORK_DIR,'output.mp4'),{listFile,totalSeconds}=await renderSequence(q,top),frameCount=Math.round(totalSeconds*25),zoomStep=(.06/frameCount).toFixed(6),fc=`[0:v]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,zoompan=z='min(zoom+${zoomStep},1.06)':d=${frameCount}:s=1080x1920:fps=25[bg];[bg][2:v]overlay=0:0:format=auto[v];[1:a]volume=-18dB,afade=t=in:st=0:d=0.5[a]`;execSync(`ffmpeg -y -loop 1 -i "${image}" -stream_loop -1 -i "${BGM_FILE}" -f concat -safe 0 -i "${listFile}" -filter_complex "${fc}" -map "[v]" -map "[a]" -t ${totalSeconds.toFixed(2)} -c:v libx264 -preset veryfast -crf 20 -pix_fmt yuv420p -c:a aac -b:a 128k -shortest "${out}"`,{stdio:'inherit'});return out}
function buildDescription(hook){return `${hook}\n\n✨ ప్రతిరోజూ ఒక కొత్త జీవిత సత్యం కోసం ఈ ఛానల్‌ని ఫాలో అవ్వండి.\nమీకు ఈ మాట నచ్చిందా? కామెంట్ చేసి చెప్పండి 💬\n\n#TeluguQuotes #JeevithaSatyalu #TeluguMotivation #LifeWisdom #TeluguShorts #MotivationalQuotes #InspirationalQuotes #TeluguStatus #Shorts`}
async function upload(video,title,hook){const auth=new google.auth.OAuth2(YT_CLIENT_ID,YT_CLIENT_SECRET);auth.setCredentials({refresh_token:YT_REFRESH_TOKEN});const yt=google.youtube({version:'v3',auth});const r=await yt.videos.insert({part:['snippet','status'],requestBody:{snippet:{title:title.slice(0,95),description:buildDescription(hook),categoryId:'27'},status:{privacyStatus:'private',selfDeclaredMadeForKids:false}},media:{body:fs.createReadStream(video)}});const url=`https://www.youtube.com/watch?v=${r.data.id}`,studioUrl=`https://studio.youtube.com/video/${r.data.id}/edit`;log(`Uploaded as PRIVATE (pending your review): ${url}`);fs.mkdirSync(WORK_DIR,{recursive:true});fs.writeFileSync(REVIEW_FILE,`## Review required before publishing\n\n- Title: ${title}\n- Watch (private): ${url}\n- Edit in Studio: ${studioUrl}\n\nCheck the Telugu text, image and audio, then set visibility to Public yourself in YouTube Studio to publish.`,'utf8')}
async function main(){fs.mkdirSync(WORK_DIR,{recursive:true});const q=await makeQuote();log(`SCREEN (${countWords(q.screen)}w): ${q.screen}`);log(`HOOK: ${q.hook}`);log(`HIGHLIGHT: ${(q.highlightWords||[]).join(', ')||'(none)'}`);const image=await makeImage(q.image),top=q.topLabel||pickTopLabel(q.mood);log(`TOP LABEL: ${top}`);const video=await render(image,q,top),titleWithEmoji=`${pickEmoji(q.mood)} ${q.title}`;await upload(video,titleWithEmoji,q.hook);saveState(q.title,q.screen,q.image)}main().catch(e=>{console.error('FAILED:',e.stack||e);process.exit(1)});